version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "./"
    schedule:
      interval: "weekly"
    labels:
      - "dependency"
      - "github-actions"
    commit-message:
      prefix: "actions"

  - package-ecosystem: "nuget"
    directory: "./DotMP-Tests/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency"
      - "nuget"
    commit-message:
      prefix: "nuget"

  - package-ecosystem: "nuget"
    directory: "./DotMP/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency"
      - "nuget"
    commit-message:
      prefix: "nuget"
  
  - security-advisories:
    open-pull-requests-limit: 10
