name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Run integration tests
      run: dotnet test --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover DotMP-Tests
    - name: Upload codecov artifact
      uses: actions/upload-artifact@v3
      with:
        name: codecov-xml
        path: DotMP-Tests/coverage.net6.0.opencover.xml
        retention-days: 1

  codecov:
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
    - name: Download codecov artifact
      uses: actions/download-artifact@v3
      with:
        name: codecov-xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.net6.0.opencover.xml
        token: ${{ secrets.CODECOV_TOKEN }}
