name: Documentation

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Update GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Generate Patched README
        run: make ProcessedREADME.md
      - name: Deploy GitHub Pages
        uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
