name: Integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build main project
      run: make build
    - name: Build tests
      run: make tests
    - name: Build examples
      run: make examples

  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Run integration tests
      run: dotnet test --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover DotMP-Tests

  codecov:
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      files: ./DotMP-Tests/coverage.net6.0.opencover.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
